source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'AMResizingTextView_Abstract_Target' do
    pod 'AMResizingTextView', :path => '../'

    target 'AMResizingTextView_Example' do
    end

    target 'AMResizingTextView_Tests' do
        pod 'Nimble', '~> 7.3'
    end
end
